// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CopyToClipboard(arg1) {
  return window['go']['main']['App']['CopyToClipboard'](arg1);
}

export function DeleteRecording(arg1) {
  return window['go']['main']['App']['DeleteRecording'](arg1);
}

export function GetAudioURL(arg1) {
  return window['go']['main']['App']['GetAudioURL'](arg1);
}

export function GetRecordings() {
  return window['go']['main']['App']['GetRecordings']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetSummary(arg1) {
  return window['go']['main']['App']['GetSummary'](arg1);
}

export function GetTranscript(arg1) {
  return window['go']['main']['App']['GetTranscript'](arg1);
}

export function NameRecording(arg1, arg2) {
  return window['go']['main']['App']['NameRecording'](arg1, arg2);
}

export function PauseRecording() {
  return window['go']['main']['App']['PauseRecording']();
}

export function ResumeRecording() {
  return window['go']['main']['App']['ResumeRecording']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function StartRecording() {
  return window['go']['main']['App']['StartRecording']();
}

export function StopRecording() {
  return window['go']['main']['App']['StopRecording']();
}

export function TranscribeAndSummarize(arg1) {
  return window['go']['main']['App']['TranscribeAndSummarize'](arg1);
}
