// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CopyToClipboard(arg1:string):Promise<void>;

export function DeleteRecording(arg1:string):Promise<void>;

export function GetAudioURL(arg1:string):Promise<string>;

export function GetRecordings():Promise<Array<main.Recording>>;

export function GetSettings():Promise<main.Settings>;

export function GetSummary(arg1:string):Promise<string>;

export function GetTranscript(arg1:string):Promise<string>;

export function NameRecording(arg1:string,arg2:string):Promise<main.Recording>;

export function PauseRecording():Promise<void>;

export function ResumeRecording():Promise<void>;

export function SaveSettings(arg1:main.Settings):Promise<void>;

export function StartRecording():Promise<void>;

export function StopRecording():Promise<string>;

export function TranscribeAndSummarize(arg1:string):Promise<void>;
